import "/src/app/styles/global.css";
import Navigation from "./navigation";
import Footer from "./footer";

import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Read · Y",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navigation />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
