import React from "react";
import ReactDOM from "react-dom";

import "/src/app/styles/global.css";
import Navigation from "./navigation";
import Footer from "./footer";

export const metadata = {
  title: "Read · Y",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
